### ISSUE TITLE
[QUESTION] Always redirect after opening app

### ISSUE THREAD

**Issue by ezerway** [ctrlaltdylan/shopify-session-tokens-nextjs#11]
I tried `nextjs-toolbox-v2`, it works but it always forces auth api calling, and create new access token.
Do you have any idea to solve the inconvenience. Thank you.

##### Video
https://monosnap.com/file/zobRX8aALPlL5CGBJlMmgZH9iNY2qN

**Comment by tilomitra** [comment]
I am having this issue as wek. Any thoughts @ctrlaltdylan ?

**Comment by ctrlaltdylan** [comment]
Hi, can you describe this issue further?

What's the requested behavior?

Provide a code sample as well?


From what I can tell, you the AppBridge needs OAuth to begin the SessionToken authentication. So on page refreshes it should verify that the client is OAuth'd but not necessarily go through the flow of asking for scopes etc.

Some more details on what you mean be force API calling would be helpful to understand what's going on.

**Comment by ctrlaltdylan** [comment]
Please upgrade to the official v2 tag of the `shopify-nextjs-toolbox` package and let me know if this is resolved.

**Comment by hrstrand** [comment]
I am seeing the exact same behavior on latest shopify-nextjs-toolbox version. 

I copied the example app and converted it to typescript. Running it as a custom nextjs server, but passing all requests to the default handler : 


```
import next from "next"; 
import { createServer } from "http"
import { parse } from "url"

const dev = process.env.NODE_ENV !== "production";
const app = next({
  dev,
});
console.log("STARTING APP")
const handle = app.getRequestHandler()
const hostname = 'localhost'
const port = 3000 
app.prepare().then(async () => {

  createServer(async (req, res) => {
    try {
      // Be sure to pass `true` as the second argument to `url.parse`.
      // This tells it to parse the query portion of the URL.
      const parsedUrl = parse(req.url, true)
      const { pathname, query } = parsedUrl

      if (pathname === '/a') {
        await app.render(req, res, '/a', query)
      } else if (pathname === '/b') {
        await app.render(req, res, '/b', query)
      } else {
        await handle(req, res, parsedUrl)
      }
    } catch (err) {
      console.error('Error occurred handling', req.url, err)
      res.statusCode = 500
      res.end('internal server error')
    }
  }).listen(port, () => {
   // if (err) throw err
    console.log(`> Ready on http://${hostname}:${port}`)
  })

  
})
```
<img width="1368" alt="Screenshot 2022-03-11 at 10 31 19" src="https://user-images.githubusercontent.com/502527/157840449-deb0ea2e-54ea-4806-80c4-b9a5205204b0.png">

**Comment by hrstrand** [comment]
Comment to above -- tried removing the custom server, running it with "next dev" as the example app. Same behavior

**Comment by hmpws** [comment]
Not an expert on OAuth by any means, is it possible to skip OAuth if an accessToken is provided? Trying to solve this redirect behavior as well.

I see this in the example code but where is the accessToken checked for in the OAuth process?:
```  
// save accessToken with the shop
db.collection("shop").insertOne({ name: req.query.shop, accessToken });
```
