### ISSUE TITLE
Error at the start of OAuth flow

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [ctrlaltdylan/shopify-session-tokens-nextjs#14]
Hello @ctrlaltdylan ,
First of all thanks so much for this awesome repo, using Koa custom server doesn't really make a huge sense with next js.

second, I have implemented the steps in read me and trying to start the auth flow by visiting my app url with shop param like `https://app.ahmed.wiki/?shop=my-shop.myshopify.com` i get the below error when call the`/auth` api 
```
{"message":"Unauthorized: shop missing from query string."}
```
looking into the network tab found the following
<img width="400" alt="Screen Shot 2021-11-01 at 11 00 42 PM" src="https://user-images.githubusercontent.com/36244069/139784953-91b84eef-fd71-4b0a-bcde-c915be64de60.png">

so I had to start the flow by visiting `https://app.ahmed.wiki/?a=1&shop=my-shop.myshopify.com` and adding `a=1` as it seems the library adds `?` to the first query param and the rest of params being read correctly. After doing this everything works correctly. 

any ideas on how to get rid of my hack `a=1` param?

Thanks so much

**Comment by ctrlaltdylan** [comment]
Hi @ahmed-adly-khalil can you please provide your ENV variables for the OAuth start? (not the sensitive ones like private keys)

I'm thinking the trailing `/` in `https://app.ahmed.wiki/` might be causing an issue here.

**Comment by ahmed-adly-khalil** [comment]
@ctrlaltdylan sure, here is the content of `.env.local`

SHOPIFY_API_PUBLIC_KEY=000
SHOPIFY_API_PRIVATE_KEY=000
NEXT_PUBLIC_SHOPIFY_API_PUBLIC_KEY=000
SHOPIFY_AUTH_CALLBACK_URL=https://app.ahmed.wiki/api/auth/callback
SHOPIFY_AUTH_SCOPES=000
HOME_PATH=/home

there are other unrelated keys, and i have tried to hit `https://app.ahmed.wiki?shop=myshop.myshopify.com` and it keep redirecting to `https://app.ahmed.wiki/?shop=myshop.myshopify.com`

**Comment by ahmed-adly-khalil** [comment]
@ctrlaltdylan any ideas for this one? is there something I need to change at my end? Thanks so much

**Comment by ctrlaltdylan** [comment]
@ahmed-adly-khalil could you please write a jest spec to show the bug? It could be a configuration issue with your settings on Shopify vs what's in the .env.local. I have not seen this bug myself.
