### ISSUE TITLE
TypeError. pages is undefined

### ISSUE THREAD

**Issue by hankmander** [ctrlaltdylan/shopify-session-tokens-nextjs#4]
When opening my app I often see this screen flash by for a second before the app redirects. It then seems to work as expected. This is when running `npm run dev` on my local machine.

![2021-04-23_12-15](https://user-images.githubusercontent.com/846469/115859714-dd1d4300-a430-11eb-8d0d-f79729f470cf.png)

Then when actually running this in production on Vercel I'm always met by this screen on a cold boot. If vercel is warm, like if I try one more time, it works as expected. I am not redirected when this screen shows up however, the user is stranded here. This got my app rejected by Shopify yesterday since they couldnt install it. I wonder if this is related somehow? Or does anybody know anything about why this shows up? I've been checking the source code for `shopify-nextjs-toolbox` but can't find anything.
![unnamed](https://user-images.githubusercontent.com/846469/115860300-99770900-a431-11eb-87e4-d32ef55fde08.png)

**Comment by hankmander** [comment]
I just rolled all the way back to the latest [commit by the maintainer](https://github.com/ctrlaltdylan/shopify-session-tokens-nextjs/commit/03049a5f297268cb5f24e1f391cb9e021a06a0af) and I still get the same errors when installing the app. Is this something new in the Shopify platform?

**Comment by ctrlaltdylan** [comment]
@hankmander you most likely have a variable called `pages` you're accessing _before_ it's instantiated.

The `shopify-next-js-toolbox` does not have a `pages` variable. This is why I believe it's an issue in your codebase and not in the project.

**Comment by hankmander** [comment]
I thought so too at first. But just running the code from the latest [commit](https://github.com/ctrlaltdylan/shopify-session-tokens-nextjs/commit/03049a5f297268cb5f24e1f391cb9e021a06a0af) of this very repo, with no code added, gets me the same error. Using the Shopify app Bridge like in [this pull request](https://github.com/ctrlaltdylan/shopify-session-tokens-nextjs/pull/5) solved my issue.
