### ISSUE TITLE
/auth/callback not found

### ISSUE THREAD

**Issue by dgtlmonk** [ctrlaltdylan/shopify-session-tokens-nextjs#7]
Hi, 

I can't seem get this to work. I'm getting `/auth/callback` not found from ngrok :-/

![image](https://user-images.githubusercontent.com/43092/117820496-30025180-b29d-11eb-9b24-3767d4b6f50c.png)

**Comment by ctrlaltdylan** [comment]
The issue tracking on this repo will only be used for improvements or bug reports that are reproducible by example code.

Screenshots are not sufficient to prove that this is an implementation problem or a library problem.

**Comment by sroettering** [comment]
@dgtlmonk The callback handler is under `/api/auth/callback` not under `/auth/callback`. You need to adjust the redirect URL in your app settings.

**Comment by dgtlmonk** [comment]
Yeah figured that out. Thank you Even 😁
