### ISSUE TITLE
client undefined?

### ISSUE THREAD

**Issue by dgtlmonk** [ctrlaltdylan/shopify-session-tokens-nextjs#8]
Hi :)

I'm getting api_key undefined when I try to install the app. Although I'm pretty sure i have the  .env.local setup?  
I have to manually put the client id value (api key) to make the setup work. 
![image](https://user-images.githubusercontent.com/43092/117821031-ba4ab580-b29d-11eb-8cd8-282454d2ed96.png)

**Comment by ctrlaltdylan** [comment]
The issue tracking on this repo will only be used for improvements or bug reports that are reproducible by example code.

Screenshots are not sufficient to prove that this is an implementation problem or a library problem.
