### ISSUE TITLE
Empty auth callback handler

### ISSUE THREAD

**Issue by sroettering** [ctrlaltdylan/shopify-session-tokens-nextjs#9]
I'm playing around with this example repo because the code generated by the shopify-cli does not work for me.
I found the empty auth callback handler with a comment `save accessToken with the shop`. What would I use this token for and where would I store it preferably?

Another question: The code from the shopify-cli (using a koa server) stored app installations and used that for redirecting the user to the authentication endpoint if a new installation was encountered. Do I need to implement this as well when using the toolbox?

**Comment by ctrlaltdylan** [comment]
Hi @sroettering 

The access token is the private server side token that represents your access to the store on Shopify Admin API - constrained by the scopes you requested during OAuth.

This library doesn't provide an opinion on what database your app uses to store this token for future use.

The 2nd part of your question I'm not so familiar with. I would need more context, but this example covers normal public app authentication.
